### ISSUE TITLE
500 error on auth/sso when trying to run initial configuration

### ISSUE THREAD

**Issue by criscmaia** [directus/api#1117]
# Bug Report

## Steps to Reproduce

1, LAMP ([Linux on WSL](https://medium.com/@ssharizal/how-to-install-lamp-stack-server-on-windows-subsystem-linux-wsl-windows-10-133419c22473))
2. sudo apt-get update && sudo apt-get upgrade
3. sudo apt-get install lamp-server^
4. Update etc/apache2/apache2.conf:
```
Servername localhost
AcceptFilter http none
```
5. MySQL removed as I had it on a server already
6. sudo apt-get install php-curl
7. VirtualHost configuration:
```
*:80                   localhost (/etc/apache2/sites-enabled/000-default.conf:1)
*:8080                 example.com (/etc/apache2/sites-enabled/000-default.conf:34)
```
8. git clone https://github.com/directus/directus.git
9. sudo chown www-data -R /var/www/directus
10. sudo chown www-data -R /var/www/directus/public/upload
11. Boilerplate System Database from /src/schema.sql

## Expected Behavior
Load http://localhost:8080/admin to get the configuration page

## Actual Behavior
It goes to the login page instead. Error message on the console:
![image](https://user-images.githubusercontent.com/9072422/61205886-187dd000-a6e9-11e9-996e-0dba39b66932.png)

## Other Context & Screenshots
![image](https://user-images.githubusercontent.com/9072422/61205931-2e8b9080-a6e9-11e9-8753-777ec9db2b60.png)

## Technical Details
Window 10 Enterprise 1903
WSL Ubuntu 18.04.02
Apache 2.4.29
PHP 7.2.19
MySQL

**Comment by xeonicca** [comment]
> I also have this issue. I just followed `https://docs.directus.io/getting-started/installation.html#setup`
> 
> When it says "Navigate your browser to the App at /admin", this is what I got:
> 
> ![image](https://user-images.githubusercontent.com/3615746/61226835-c6bf5f00-a755-11e9-99bf-0910a3dfc33d.png)
> 
> Note: I have no problem installing the standalone api and app.

I encountered this error with a fresh LAMP droplet from digital ocean and fresh install. After battling this for several hours the error somehow went away when I followed the steps described here: https://docs.directus.io/advanced/api/configuration.html#configure-with-script

I ran the same script `bin/directus install:config -n <database-name> -u <mysql-user> -p <mysql-password> -N <project name>`. Note the -N params at the end, this was what caused the error for me if not specified.

Hope this helps.

**Comment by bjgajjar** [comment]
@savedario @dapertutto 

You will able to find your path related solution in PR #1096

> should be something like:
> `'settings' => !empty($appConfig['settings']) ? $appConfig['settings'] : null,`

It is fixed in #1116

Thus when we deploy our new release you guys will not able to find these issues.

**Comment by criscmaia** [comment]
> Seeing you populated the database manually, "Load http://localhost:8080/admin to get the configuration page" is not expected to happen.
> 
> Are there any PHP errors in either the `/logs` folder of the API or the server logs in general?

The /admin didn't load even before I have populated the DB.

No files inside /log

**Comment by mvorisek7** [comment]
I am still having this issue. I too do not have anything logging into the directus/logs folder. There are no errors in the error_log for apache either. I have a api.php file that is setup for the database too, but whenever I got to the /admin page, I immediately get a 500 (Internal Server Error) from /_/auth/sso, and then the same error when I type in the email and password and submitted but its for the /_/auth/authenticate endpoint instead.
Not really sure what the issue is at this point. Any help would be appreciated.

**Comment by shim-sao** [comment]
It is the same for me, I want to test Directus but the error occur just at the first attempt. I will try again when the bug will be fix.
