### ISSUE TITLE
Cannot make multiple updates to WYSIWYG interface options.

### ISSUE THREAD

**Issue by loganaaaflag** [directus/api#1765]
Hey!

I'm having issues making multiple changes to the interface options when using the WYSIWYG interface. It seems like I can only save a change to the options once. Any subsequent changes result in an error and don't stick.

To reproduce:

1. Navigate to [the demo](https://demo.directus.io) and log in.
2. Navigate to Settings -> collections -> news
3. Click the ```body``` field and toggle a toolbar option.
4. Save
5. Repeat step 3 & 4
6. An error occurs

**Comment by rijkvanzanten** [comment]
@directus/api I'm getting a 422:

```json
{
  "error": {
    "code": 404,
    "message": "Statement could not be executed (42000 - 1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '(16777215) Null' at line 1)"
  }
}
```

@hemratna I feel like it might be related to https://github.com/directus/api/pull/1601 again..

**Comment by hemratna** [comment]
@loganaaaflag 
I fixed this issue with PR #1764.
Please check it and if issue is solved then close it.

**Comment by rijkvanzanten** [comment]
Fixed in https://github.com/directus/api/pull/1764

**Comment by HashemKhalifa** [comment]
@rijkvanzanten the issue still exists with version 8.6.0

I cant add options to the wysiwyg interface like select font size, copy, etc...

**Comment by hemratna** [comment]
@HashemKhalifa Can you please verify at https://demo.directus.io?

**Comment by HashemKhalifa** [comment]
@hemratna same issue still exists, check any of the toolbar options, nothing reflects.

no consol errors or network requests made when you select any of the toolbar options.

https://demo.directus.io/admin/#/thumper/settings/interfaces/wysiwyg
