### ISSUE TITLE
Mail not working

### ISSUE THREAD

**Issue by Nitwel** [directus/api#502]
### The request
![grafik](https://user-images.githubusercontent.com/22577866/47252147-ff890c80-d43f-11e8-8a34-365df3711ca5.png)

### When using SMTP
![grafik](https://user-images.githubusercontent.com/22577866/47252126-b89b1700-d43f-11e8-987b-2d75c026d7c3.png)

### When using Sendmail
![grafik](https://user-images.githubusercontent.com/22577866/47252121-97d2c180-d43f-11e8-9856-b46e392cacfe.png)

**Comment by Marcnuth** [comment]
+1, same error happens to me. I use SMTP in mail configurations and the same error log shows as @Nitwel posted.

**Comment by WellingGuzman** [comment]
Hey @Nitwel and @Marcnuth, what version of the API are you using? It looks like this should've been fixed by https://github.com/directus/api/commit/16b21b17840580171a02af587945a351ef00ff32

Try the latest version and let me know if the issue continues.

**Comment by Nitwel** [comment]
Nope, thats why the issue is here. in the latest version 2.0.2 the bug should be fixed but it seems, that it still does not work properly

**Comment by WellingGuzman** [comment]
@Nitwel I will give it a look tomorrow, it seems then I may break it again somehow.

**Comment by Marcnuth** [comment]
@WellingGuzman , I am using the latest release v2.0.2. The same as @Nitwel .

**Comment by WellingGuzman** [comment]
Hey @Nitwel + @Marcnuth,

I pushed a [patch](https://github.com/directus/api/commit/b8e1af0823c75a7ddf840862360f66474e9ffcee) to the `master` branch to fix the problem sending mail, please when you have time confirm whether it's working in your end.

**Comment by benhaynes** [comment]
Thanks Welling. We'll consider this closed, if anyone still has an issue let us know and we'll re-open!

**Comment by Marcnuth** [comment]
@WellingGuzman  @benhaynes 

I tested the forgetPassword with the latest version. This time, the email does be sent. But there are still some other issues:

# 1: The app page show "Unknown error, try again later" even if I received the email.

![image](https://user-images.githubusercontent.com/4936388/47704148-a26e3180-dc5d-11e8-84a5-1eb20fe622fc.png)


# 2. The forget password link in the email is invalid, which miss the part of host and port:

![image](https://user-images.githubusercontent.com/4936388/47704207-ce89b280-dc5d-11e8-9b29-7c928dff4bff.png)


Thanks for all your time to handle this.

**Comment by WellingGuzman** [comment]
Hey @Marcnuth, what's that app http request response? Wondering why the error could be.

We need to look into the email templating, to see what's causing the missing host in the url.

**Comment by WellingGuzman** [comment]
@Marcnuth I have fixed the host missing from the url in the email, plus added `http://localhost` as default.

@rijkvanzanten It seems the app is expecting data from the API when the user use the "forgot password" form. It returns a status of `204 Not Content`.
