### ISSUE TITLE
Can't upload logo in Global Settings

### ISSUE THREAD

**Issue by jameswill** [directus/api#624]
Hi,

I was trying to upload logo in Global Settings in Directus 7.0.8 version and it gives error stating "Attempting to write an array as the value for field "value" in "directus_settings"" 

On checking error log file, I found [2018-11-20 12:23:45] api[_].ERROR: Directus\Database\Exception\SuppliedArrayAsColumnValue: Attempting to write an array as the value for field "value" in "directus_settings" in {path}/{To}/{directus708}/src/core/Directus/Database/TableGateway/BaseTableGateway.php:1737

Also while updating color from the global settings, it gives "scope: This value should not be blank." error.

[2018-11-20 12:26:16] api[_].ERROR: Directus\Validator\Exception\InvalidRequestException: value: This value should not be blank. in {path}/{To}/{directus708}/src/core/Directus/Services/AbstractService.php:188

What is causing this ?

**Comment by stickgrinder** [comment]
@WellingGuzman many thanks for this information. I'll try ASAP.

**Comment by rijkvanzanten** [comment]
@WellingGuzman @stickgrinder We've also recently added a `update DB` button in the settings menu if you prefer doing it from the admin app 😄

**Comment by WellingGuzman** [comment]
@stickgrinder Let us know if that worked for you. You also need to get the most recent version of your Directus in order to get the latest migration files used to upgrade the database.

**Comment by stickgrinder** [comment]
OK, I just updated to the last docker images: I'm now running API v2.0.10 and application 7.0.10.

I upgraded the database both via the button in the app admin section that running `bin/directus db:upgrade` inside the container.

Still when I try to upload a file via backend, a flash message says `Attempting to write an array as the value for field "value" in "directus_settings"`.

Did I miss something?

**Comment by rijkvanzanten** [comment]
@stickgrinder nah that's the issue @wellingguzman is solving:

> I will work on making each setting record match their directus_fields type.

The one solved by updating the DB was the missing column `scope` 🙃

**Comment by stickgrinder** [comment]
It was a bit confusing actually... I didn't get the reason to update the DB then :sweat_smile: sorry!
Anyway, great to see that the docker images are working like a charm! :smile:

**Comment by jameswill** [comment]
Hi,

Issue still persists in Directus 7.0.11 version as well.

**Comment by kjj77** [comment]
Hi guys,

I've installed the Directus suite, I've **updated to the latest git commit**  (b0c93e7189a0a7a5292d8e9d265fc1b69d09150c) and I'm having too the same error while trying to save the logo :

**Attempting to write an array as the value for field "value" in "directus_settings"**

**Tried to update DB via the admin app**, nothing has changed either.
This is being tested on an AWS EC2 instance with an ordinary bitnami-lampstack-7.1.22-1-r40-linux-ubuntu-16.04-x86

**Comment by stickgrinder** [comment]
Did you guys run a `db:upgrade`?

**Comment by kjj77** [comment]
Just run it and re-tested it, same error though

**Comment by benhaynes** [comment]
I've just elevated today to the high priority board. We'll look into what's going on here first thing tomorrow (@WellingGuzman is off today).

**Comment by WellingGuzman** [comment]
This still is a problem that we need to fix. we will try to fix it as soon as possible. I will keep you all posted.

**Comment by devninjajeremy** [comment]
Has this been fixed? I'm getting the same issue when trying to upload a logo. I have a fresh master branch installed. I'm nervous to switch to the development branch because this is running in production currently for a client.

**Comment by benhaynes** [comment]
Still working on this one @devninjajeremy — though it's high on our list.

**Comment by benhaynes** [comment]
I've added this to the 7.0.15 project board — we'll get it resolved this Monday!

**Comment by carolin-skiply** [comment]
Hi guys,
I am having the same issue with the logo as well. Any idea on a temporary fix ?

**Comment by WellingGuzman** [comment]
At the moment there's not temporary fix.

**Comment by gamito** [comment]
Hi, guys.
Is there is any progress on this?
Thank you.

**Comment by rijkvanzanten** [comment]
Hey @gamito! This was actually fixed just now in https://github.com/directus/api/pull/821 😄

**Comment by justrealmilk** [comment]
Experiencing this error on 7.1 with `Thumbnail Quality Tags` and `Thumbnail Actions`

**Comment by RVaniuta** [comment]
Have same issue with Thumbnail Quality Tags and Thumbnail Actions too

**Comment by victormidp** [comment]
Still having the problem with the current latest version. Now, the logo gets 'saved' but the interface never shows it

**Comment by theharshin** [comment]
The logo is being saved successfully. Just need to change some variables on APP side to reflect it. This PR should fix it. https://github.com/directus/app/pull/1510
